### ISSUE TITLE
Pm2 monit alternative

### ISSUE THREAD

**Issue by Lucienest** [w-xuefeng/pmb#1]
I want to know the pm2 monit's alternative that shows an in-console-ui to print all stdout logs and
current stats
pmb log doesn't do that

**Comment by w-xuefeng** [comment]
> I want to know the pm2 monit's alternative that shows an in-console-ui to print all stdout logs and current stats pmb log doesn't do that

The `pmb monit` is planned and will be implemented gradually in the future.
Thank you for your attention.

**Comment by w-xuefeng** [comment]
done
